_BASE_: "Base-CondInst.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: "checkpoints/CondInst_MS_R_50_1x.pth"
  # uses a stronger pretrained model on COCO.
  WEIGHTS: "checkpoints/CondInst_MS_R_50_3x.pth"
  RESNETS:
    DEPTH: 50
#OUTPUT_DIR: "output/condinst_MS_R_50_1x"
  ROI_HEADS:
    NUM_CLASSES: 8
  SEM_SEG_HEAD:
    NUM_CLASSES: 8
  BASIS_MODULE:
    NUM_CLASSES: 8
  FCOS:
    NUM_CLASSES: 8
  # RETINANET:
  #   NUM_CLASSES: 2
OUTPUT_DIR: "training_dir/COCO_pretrain_strong/CondInst_MS_R_50_1x_kitti_mots"

DATASETS:
  # TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
  TRAIN: ("bdd_mots_train",)
  TEST: ("bdd_mots_val",)
SOLVER:
  #IMS_PER_BATCH: 16
  #BASE_LR: 0.01
  #STEPS: (60000, 80000)
  #MAX_ITER: 90000
  #2 imgs per gpu.
  #here IMS_PER_BATCH is the total batch_size including all gpus.
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: []
  MAX_ITER: 42000
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 500
