import numpy as np
import pickle,os
from pathlib import Path
from tqdm import tqdm

# this file reid_feat_to_strong_sort.py is to
# convert reid feat generated by my condinst+ReID to strong_sort project.
# need to do reid feat normalization, since it's normed in strong_sort.
# norm is used for original deepsort reid model, its reid feat is already normed.
# norm is not necessary, since BoT ReID feat is not normed either.
# need to check the frame_start id, since it's 1 in MOT17, but 0 in KITTI MOTS.

# npy format: frame,-1,x,y,w,h,score,-1,-1,-1,feature-128d.
# all in float64.

def deal_seq_one_del_nan(seq_id,pkl_content):
    """Remove the nan reid feat and paired box generated by mask pool reid.
    """
    def choose_seq_one(seq_id,pkl_content):
        def choose_seq_id(line_one,seq_id):
            if int(line_one['img_info']['file_name'].split('/')[-2])==seq_id:
                return True
            return False
        seq_one=list(filter(lambda x: choose_seq_id(x,seq_id),pkl_content))
        return seq_one
    seq_one=choose_seq_one(seq_id=seq_id,pkl_content=pkl_content)
    # change line one to numpy.
    list_seq_one=[]
    for line_one in seq_one:
        frame_id=float(Path(line_one['img_info']['file_name']).stem)
        x,y=line_one['pred_box_ori_size'][0][0],line_one['pred_box_ori_size'][0][1]
        w,h=line_one['pred_box_ori_size'][0][2]-x,line_one['pred_box_ori_size'][0][3]-y
        score=line_one['box_score']
        feat=line_one['reid_feat']
        # in fact, the reid feat nan doesn't make any difference in DeepSORT,
        # since the pred_box score is low like 0.2, and the reid feat nan and its paired pred_box
        # would be removed in DeepSORT at the beginning.
        if np.isnan(feat).any():
            continue
        line_one_np=np.concatenate(([frame_id,-1,x,y,w,h,score,-1,-1,-1],feat),dtype=np.float64)
        list_seq_one.append(line_one_np)
    # for 1d array, can't replace np.vstack with np.concatenate.
    np_seq_one=np.vstack(list_seq_one)
    return np_seq_one

if __name__=="__main__":
    
    file_path="../my_data/reid_one_class_infer_pair_warp_right_track/COCO_pretrain_strong/search_for_loss_combination/long_epoch_seq_shuffle_fl_2_lr_0_0001_bs_4_eval_40_no_color_sim_pretrain_weights_v3_time_7/BoxInst_MS_R_50_1x_kitti_mots/reid_infer_and_eval_out/iter_0007919/reid_infer_out.pkl"
    with open(file_path,"rb") as f:
        pkl_content_ori=pickle.load(f)
        
    # seperate car:0/pedestrian:1
    cat={'car':0,'pedestrian':1}
    for cat_choose in cat.keys():
        class_id=cat[cat_choose]
        pkl_content=list(filter(lambda x: x['pred_class']==class_id,pkl_content_ori))
        # get seq id.
        file_name_list=[x['img_info']['file_name'] for x in pkl_content]
        seq_id_list=np.unique([int(x.split('/')[-2]) for x in file_name_list])
        
        out_dir="../my_data/reid_one_class_infer_pair_warp_right_track/COCO_pretrain_strong/search_for_loss_combination/long_epoch_seq_shuffle_fl_2_lr_0_0001_bs_4_eval_40_no_color_sim_pretrain_weights_v3_time_7/BoxInst_MS_R_50_1x_kitti_mots/reid_np/iter_0007919/"+cat_choose
        os.makedirs(out_dir,exist_ok=True)
        for seq_id in tqdm(seq_id_list):
            np_seq_one=deal_seq_one_del_nan(seq_id,pkl_content)
            out_path=out_dir+'/'+str(seq_id).zfill(4)+'.npy'
            np.save(out_path,np_seq_one)
    
    print('kk')

