# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
from .fcos import FCOS
from .blendmask import BlendMask
from .backbone import build_fcos_resnet_fpn_backbone
from .one_stage_detector import OneStageDetector, OneStageRCNN
from .roi_heads.text_head import TextHead
from .batext import BAText
from .MEInst import MEInst
from .condinst import condinst
from .solov2 import SOLOv2
from .fcpose import FCPose
# below by cws
# need to add below to register.
from .condinst_reid import CondInst_ReID
from .condinst_reid_one_class import CondInst_ReID_One_Class
from .condinst_reid_sem_hard import CondInst_ReID_Sem_Hard
from .condinst_reid_one_class_eval import CondInst_ReID_One_Class_Eval
from .condinst_reid_one_class_infer import CondInst_ReID_One_Class_Infer
from .fcos_reid_one_class_infer import FCOS_ReID_One_Class_Infer
from .condinst_reid_one_class_mask_pool_infer import CondInst_ReID_One_Class_Mask_Pool_Infer
from .condinst_reid_one_class_gt_mask_pool_infer import CondInst_ReID_One_Class_GT_Mask_Pool_Infer
from .condinst_reid_one_class_gt_mask_pool_eval import CondInst_ReID_One_Class_GT_Mask_Pool_Eval
from .condinst_reid_one_class_gt_mask_pool_infer_reid_eval import CondInst_ReID_One_Class_GT_Mask_Pool_Infer_ReID_Eval
from .condinst_reid_one_class_cost_vol_infer import CondInst_ReID_One_Class_Cost_Vol_Infer
from .condinst_reid_one_class_infer_opt_flow import CondInst_ReID_One_Class_Infer_Opt_Flow
from .condinst_reid_one_class_infer_opt_flow_learn_loss import CondInst_ReID_One_Class_Infer_Opt_Flow_Learn_Loss
from .condinst_reid_one_class_infer_opt_flow_deform_conv import CondInst_ReID_One_Class_Infer_Opt_Flow_Deform_Conv
from .condinst_reid_one_class_infer_opt_flow_right_aug import CondInst_ReID_One_Class_Infer_Opt_Flow_Right_Aug
from .condinst_reid_one_class_infer_pair_warp import CondInst_ReID_One_Class_Infer_Pair_Warp
from .condinst_reid_one_class_infer_car_shadow import CondInst_ReID_One_Class_Infer_Car_Shadow
from .condinst_reid_one_class_infer_pair_warp_reid_eval_in_train import CondInst_ReID_One_Class_Infer_Pair_Warp_ReID_Eval_In_Train
from .condinst_reid_one_class_infer_bdd_pair_warp import CondInst_ReID_One_Class_Infer_BDD_Pair_Warp
from .condinst_reid_one_class_infer_bdd_pair_warp_reid_eval_in_train import CondInst_ReID_One_Class_Infer_BDD_Pair_Warp_ReID_Eval_In_Train
from .condinst_reid_one_class_infer_reid_eval_in_train import CondInst_ReID_One_Class_Infer_ReID_Eval_In_Train
from .condinst_reid_one_class_infer_reid_eval_in_train_pair_triplet import CondInst_ReID_One_Class_Infer_ReID_Eval_In_Train_Pair_Triplet
from .condinst_reid_one_class_infer_pair_warp_inverse_reid_eval_in_train import CondInst_ReID_One_Class_Infer_Pair_Warp_Inverse_ReID_Eval_In_Train
from .condinst_reid_one_class_infer_pair_warp_reid_eval_in_train_for_infer import CondInst_ReID_One_Class_Infer_Pair_Warp_ReID_Eval_In_Train_For_Infer

# below for youtube vis 2019 dataset.
from .condinst_reid_one_class_infer_reid_eval_in_train_for_infer import CondInst_ReID_One_Class_Infer_ReID_Eval_In_Train_For_Infer
from .condinst_reid_one_class_infer_ytvis_pair_warp_reid_eval_in_train import CondInst_ReID_One_Class_Infer_YTVIS_Pair_Warp_ReID_Eval_In_Train
from .condinst_reid_one_class_infer_ytvis_pair_warp_reid_eval_in_train_for_infer import CondInst_ReID_One_Class_Infer_YTVIS_Pair_Warp_ReID_Eval_In_Train_For_Infer

_EXCLUDE = {"torch", "ShapeSpec"}
__all__ = [k for k in globals().keys() if k not in _EXCLUDE and not k.startswith("_")]
